name = "SPAWNTIME_MODULE"
description = "Query respawn-timers for mobs"
version = "0.1.1"
github = "Nadybot/SPAWNTIME_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^5.0.0-beta1"

[requires]
ext-Reflection = "*"
ext-pcre = "*"
ext-date = "*"
