name = "SPAWNTIME_MODULE"
description = "Query respawn-timers for mobs"
version = "0.1.4"
github = "Nadybot/SPAWNTIME_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"

[requires]
ext-pcre = "*"
ext-date = "*"
